import { NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { getUserFromRequest } from '@/lib/auth'
import { materializeRecurringBookings } from '@/lib/recurring'

type RouteParams = { params: Promise<{ id: string }> }

const DAY_NAMES = ['domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado']
const TIME_RE = /^\d{2}:\d{2}$/

function todayStr(): string {
  const t = new Date()
  t.setHours(12, 0, 0, 0)
  return `${t.getFullYear()}-${String(t.getMonth() + 1).padStart(2, '0')}-${String(t.getDate()).padStart(2, '0')}`
}

// PUT /api/club/recurring-bookings/[id] — Edita una reserva fija.
// Libera las ocurrencias futuras de la plantilla vieja, actualiza los datos y
// re-materializa las próximas ocurrencias con el nuevo día/horario/cancha/beneficiario.
export async function PUT(request: Request, { params }: RouteParams) {
  try {
    const clubUser = await getUserFromRequest(request)
    if (!clubUser || clubUser.role !== 'CLUB') {
      return NextResponse.json({ message: 'Unauthorized: Club access required' }, { status: 403 })
    }
    const club = await db.club.findUnique({ where: { userId: clubUser.id } })
    if (!club) return NextResponse.json({ message: 'Club not found' }, { status: 404 })

    const { id } = await params
    const recurring = await db.recurringBooking.findUnique({ where: { id } })
    if (!recurring || recurring.clubId !== club.id) {
      return NextResponse.json({ message: 'Reserva fija no encontrada' }, { status: 404 })
    }

    const body = await request.json()
    const { courtId, dayOfWeek, startTime, endTime, playerId, customerName, customerPhone } = body

    if (!courtId || typeof courtId !== 'string') {
      return NextResponse.json({ message: 'La cancha es requerida' }, { status: 400 })
    }
    if (typeof dayOfWeek !== 'number' || dayOfWeek < 0 || dayOfWeek > 6) {
      return NextResponse.json({ message: 'Día de la semana inválido' }, { status: 400 })
    }
    if (!TIME_RE.test(startTime || '') || !TIME_RE.test(endTime || '')) {
      return NextResponse.json({ message: 'Horario inválido (HH:mm)' }, { status: 400 })
    }
    const hasPlayer = !!playerId
    const hasWalkin = !!(customerName && customerName.trim())
    if (hasPlayer === hasWalkin) {
      return NextResponse.json({ message: 'Indicá un jugador o un nombre de cliente (no ambos)' }, { status: 400 })
    }

    const court = await db.court.findUnique({ where: { id: courtId } })
    if (!court || court.clubId !== club.id) {
      return NextResponse.json({ message: 'Cancha no encontrada o no pertenece a este club' }, { status: 400 })
    }

    const player = hasPlayer
      ? await db.player.findUnique({ where: { id: playerId }, include: { user: { select: { id: true } } } })
      : null
    if (hasPlayer && !player) {
      return NextResponse.json({ message: 'Jugador no encontrado' }, { status: 404 })
    }

    // Free the future occurrences generated by the OLD template
    const futureOccurrences = await db.booking.findMany({
      where: { recurringBookingId: id, slot: { day: { gte: todayStr() } } },
      select: { id: true, slotId: true },
    })

    await db.$transaction(async (tx) => {
      for (const occ of futureOccurrences) {
        await tx.booking.delete({ where: { id: occ.id } })
        await tx.slot.update({ where: { id: occ.slotId }, data: { status: 'AVAILABLE' } })
      }
      await tx.recurringBooking.update({
        where: { id },
        data: {
          courtId,
          dayOfWeek,
          startTime,
          endTime,
          playerId: hasPlayer ? playerId : null,
          customerName: hasWalkin ? customerName.trim() : null,
          customerPhone: hasWalkin && customerPhone ? customerPhone.trim() : null,
        },
      })
    })

    // Re-materialize future occurrences with the new schedule
    const materialized = await materializeRecurringBookings(club.id)

    const beneficiary = player ? `${player.firstName} ${player.lastName}` : customerName.trim()
    if (player?.user) {
      await db.notification.create({
        data: {
          userId: player.user.id,
          message: `Tu reserva fija fue actualizada: ${DAY_NAMES[dayOfWeek]} a las ${startTime} en ${court.name}.`,
          type: 'BOOKING_CONFIRMED',
          relatedId: recurring.id,
        },
      })
    }
    await db.notification.create({
      data: {
        userId: clubUser.id,
        message: `Reserva fija actualizada: ${beneficiary}, ${DAY_NAMES[dayOfWeek]} ${startTime} en ${court.name}.` +
          (materialized.conflicts.length > 0 ? ` (${materialized.conflicts.length} conflicto/s desplazado/s)` : ''),
        type: 'BOOKING_CONFIRMED',
        relatedId: recurring.id,
      },
    })

    return NextResponse.json({ success: true, conflicts: materialized.conflicts })
  } catch (error) {
    console.error('Error updating recurring booking:', error)
    return NextResponse.json({ message: 'An error occurred while updating the recurring booking' }, { status: 500 })
  }
}

// DELETE /api/club/recurring-bookings/[id] — Cancela una reserva fija.
// Libera solo las ocurrencias futuras (día >= hoy); las pasadas quedan como historial.
export async function DELETE(request: Request, { params }: RouteParams) {
  try {
    const clubUser = await getUserFromRequest(request)
    if (!clubUser || clubUser.role !== 'CLUB') {
      return NextResponse.json({ message: 'Unauthorized: Club access required' }, { status: 403 })
    }
    const club = await db.club.findUnique({ where: { userId: clubUser.id } })
    if (!club) return NextResponse.json({ message: 'Club not found' }, { status: 404 })

    const { id } = await params
    const recurring = await db.recurringBooking.findUnique({
      where: { id },
      include: { player: { include: { user: { select: { id: true } } } } },
    })
    if (!recurring || recurring.clubId !== club.id) {
      return NextResponse.json({ message: 'Reserva fija no encontrada' }, { status: 404 })
    }

    const today = new Date()
    today.setHours(12, 0, 0, 0)
    const todayStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`

    // Future occurrences (slot.day >= today) → free the slot, delete the booking
    const futureOccurrences = await db.booking.findMany({
      where: { recurringBookingId: id, slot: { day: { gte: todayStr } } },
      include: { slot: { select: { id: true } } },
    })

    await db.$transaction(async (tx) => {
      for (const occ of futureOccurrences) {
        await tx.booking.delete({ where: { id: occ.id } })
        await tx.slot.update({ where: { id: occ.slotId }, data: { status: 'AVAILABLE' } })
      }
      // Deactivate the template (kept for history of past occurrences)
      await tx.recurringBooking.update({ where: { id }, data: { active: false } })
    })

    if (recurring.player?.user) {
      await db.notification.create({
        data: {
          userId: recurring.player.user.id,
          message: `Tu reserva fija fue cancelada por el club. Las fechas futuras quedaron libres.`,
          type: 'SLOT_CANCELLED',
          relatedId: recurring.id,
        },
      })
    }

    return NextResponse.json({ success: true, freed: futureOccurrences.length })
  } catch (error) {
    console.error('Error cancelling recurring booking:', error)
    return NextResponse.json({ message: 'An error occurred while cancelling the recurring booking' }, { status: 500 })
  }
}
